### ISSUE TITLE
Navigate to previous page after logging in successfully or pressing the arrow button back to prev page.

### ISSUE THREAD

**Issue by sebxGit** [Jaffenheimer/p7-internet#108]

**Comment by NikolajKrogh** [comment]
Er det overhovedet muligt når vi bare render en ny side? Fordi hvis vi gerne, så vidt jeg forstår, vil kunne bruge ```Alt + ←```, så skal vi bruge en path at gå tilbage til og det har vi ikke når vi bare render en ny side
