### ISSUE TITLE
Add a service to connect and get answers from ETilbudsavis API

### ISSUE THREAD

**Issue by Jaffenheimer** [Jaffenheimer/p7-internet#12]
Should be added under services in the restapi

**Comment by Lildhansen** [comment]
får invalid API key når jeg sender request til etilbudsavis:
{'code': 1102, 'name': 'INVALID_API_KEY', 'id': '-XPcTExz', 'level': 'info', 'message': 'Invalid API key', 'details': 'Please set `X-Api-Key` request header or `api_key` query param'

bruger api'keyen fra den user jeg lavede med studiemail

**Comment by Lildhansen** [comment]
prøvede med den sdk ham fra etilbudsavis snakkede om (https://github.com/tjek/tjek-js-sdk/tree/develop), men bare når jeg henter den shopgun-sdk får jeg alverdens fejl, så jeg ved sku ikke helt lige

**Comment by Jaffenheimer** [comment]
Merged, closing this
