### ISSUE TITLE
Expand user table to be able to handle passwords, favourite recipes, etc.

### ISSUE THREAD

**Issue by Jaffenheimer** [Jaffenheimer/p7-internet#13]
Perhaps rethink how it should be displayed in the DB, maybe an extra table with the userid and the different recipeids stored together only

**Comment by Lildhansen** [comment]
igen, det her er jo også en del af should haves så forstår ikke hvorfor de er issues lige pt.

**Comment by Jaffenheimer** [comment]
Note: Dette skal være i et separat table

**Comment by Jaffenheimer** [comment]
Done
