### ISSUE TITLE
Add testing to backend

### ISSUE THREAD

**Issue by Jaffenheimer** [Jaffenheimer/p7-internet#157]
- [ ] Add mocks of DB (repositories) and services (UserRepo er lavet)
- [x] Test PublicControllerV1
- [x] Test services 
- [ ] Refactor mocks into separate files

**Comment by JJTM20** [comment]
> * [ ]  Add mocks of DB (repositories) and services (UserRepo er lavet)
> * [x]  Test PublicControllerV1
> * [x]  Test services

**Comment by Jaffenheimer** [comment]
Se Issue #257 så lukker denne
