### ISSUE TITLE
display the recipe that you selected in a seperate page

### ISSUE THREAD

**Issue by Lildhansen** [Jaffenheimer/p7-internet#20]

**Comment by Lildhansen** [comment]
brug react router dump

**Comment by Casper0913** [comment]
![Image](https://github.com/Jaffenheimer/p7-internet/assets/48017776/61a78987-6142-4aa9-8c50-d6edc7d85c37)

**Comment by Casper0913** [comment]
https://www.npmjs.com/package/react-router-dom

**Comment by Lildhansen** [comment]
jeg sætter det her på pause før jeg finder ud af at sende data mellem vores react objects

**Comment by Lildhansen** [comment]
nvm. im on it again!
