### ISSUE TITLE
cache ingredientpriser?

### ISSUE THREAD

**Issue by Lildhansen** [Jaffenheimer/p7-internet#22]
måske man kunne gemme ingredienspriserne, hvis der fx var et tilbud der gælder hele ugen, kunne man gemme tilbuddet og så også hvornår tilbuddet gælder fra.
det vil så nok også kræve lidt maintence af databasen, så vi får slettet de gamle tilbud.

Det vil i hvert fald gøre det nemmere hvis der skulle vises priser for alle ingredienser i alle recipes (et af vores could haves)

**Comment by Jaffenheimer** [comment]
Umiddelbart bliver det løst hvis vi bare implementere at hver gang der bliver indsat noget nyt, fjerner den dem der er over 1 uge gammel, så fremt i fald der selvfølgelig er trafik på siden, men ellers må vi argumentere for at løsningen ville virke i et real world scenario, det er ihvertfald sådan vi gør det på arbejde.

**Comment by Jaffenheimer** [comment]
Men kan godt være at vi lige skal diskutere om den skal kunne dette

**Comment by Jaffenheimer** [comment]
Done
