### ISSUE TITLE
packagelock json to gitignore

### ISSUE THREAD

**Issue by Lildhansen** [Jaffenheimer/p7-internet#48]

**Comment by Lildhansen** [comment]
forsøgte at tilføje packagelock til gitignore men git gav ikke en fuck (den trackede de changes jeg lavede i package-lock.json stadig).
tilføjede en anden fil bare for at se om jeg bare var dårlig til at gitignore, men det virkede fint.

**Comment by Casper0913** [comment]
Man skal nok fjerne filen fra github først ved brug af denne kommando:`git rm package-lock.json` or `git rm --cached package-lock.json`.
